sonar.projectKey=TsioryRobson_urbanhub-ms6-validateur
sonar.projectName=MS6 Validateur Capteur
sonar.organization=tsioryrobson
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=report_tests.xml
sonar.exclusions=tests/**,.pytest_cache/**,htmlcov/**
