sonar.projectKey=RobelManoa_urbanhub-ms-alerte
sonar.projectName=MS Alerte Usager
sonar.organization=robelmanoa
sonar.projectVersion=1.0

sonar.sources=ms-alerte-usager/src
sonar.tests=ms-alerte-usager/test/unit
sonar.exclusions=ms-alerte-usager/scripts/**,ms-alerte-usager/reports/**,ms-alerte-usager/document/**,ms-alerte-usager/coverage_html/**,ms-alerte-usager/*.xml,ms-alerte-usager/*.txt
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12.3

sonar.python.coverage.reportPaths=ms-alerte-usager/coverage.xml
sonar.python.xunit.reportPath=ms-alerte-usager/report_tests.xml
sonar.python.flake8.reportPaths=ms-alerte-usager/flake8-report.txt
